import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import ClientLayout from "../components/ClientLayout";
import { getAdminStatus } from "../utils/getAdminStatus";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Choose the required weights
  variable: "--font-poppins",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Pizza Wizza",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${poppins.variable} `}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
